-- +migrate Up
CREATE TABLE IF NOT EXISTS errorlinks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    icon_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- +migrate Down
DROP TABLE IF EXISTS errorlinks;